---
# defaults file for roles/proxmox_vm
proxmox_host: "192.168.1.135"  # Adresse de l'hôte Proxmox
proxmox_user: "root@pam"       # Utilisateur pour l'API Proxmox
proxmox_password: "landes"   # Mot de passe de l'utilisateur
proxmox_node: "pve"            # Nom du nœud Proxmox
vm_name: "OracleTest"          # Nom de la VM à créer
vm_memory: 2048                # RAM de la VM (en Mo)
vm_cores: 2                    # Nombre de cœurs CPU
vm_disk_size: 20               # Taille du disque de la VM (en Go)
vm_network: "vmbr0"            # Nom du pont réseau
vm_template: "template-ubuntu" # Nom du template de base
